/// Design system do DBook Mobile — tokens, tema e componentes compartilhados.
library;

export 'src/components/dbook_app_bar.dart';
export 'src/components/dbook_avatar.dart';
export 'src/components/dbook_button.dart';
export 'src/components/dbook_confirmation_dialog.dart';
export 'src/components/dbook_dashed_divider.dart';
export 'src/components/dbook_chip_row.dart';
export 'src/components/dbook_destination_card.dart';
export 'src/components/dbook_fare_date_strip.dart';
export 'src/components/dbook_flight_result_tile.dart';
export 'src/components/dbook_inline_status_banner.dart';
export 'src/components/dbook_legend_item.dart';
export 'src/components/dbook_loading_indicator.dart';
export 'src/components/dbook_notification_badge.dart';
export 'src/components/dbook_onboarding_slide.dart';
export 'src/components/dbook_page_indicator.dart';
export 'src/components/dbook_price_display.dart';
export 'src/components/dbook_priced_list_item.dart';
export 'src/components/dbook_qr_placeholder.dart';
export 'src/components/dbook_search_field.dart';
export 'src/components/dbook_seat_cell.dart';
export 'src/components/dbook_section_label.dart';
export 'src/components/dbook_social_login_row.dart';
export 'src/components/dbook_status_badge.dart';
export 'src/components/dbook_status_placeholder.dart';
export 'src/components/dbook_success_screen.dart';
export 'src/components/dbook_summary_row.dart';
export 'src/components/dbook_trip_summary_card.dart';
export 'src/tokens/dbook_colors.dart';
export 'src/tokens/dbook_elevation.dart';
export 'src/tokens/dbook_motion.dart';
export 'src/tokens/dbook_radius.dart';
export 'src/tokens/dbook_spacing.dart';
export 'src/tokens/dbook_typography.dart';
export 'src/theme/dbook_theme.dart';
